version: '3'
services:
  adventure:
    build:
      context: adventure-chat-front-end
      dockerfile: Dockerfile
    volumes:
      - './adventure-chat-front-end:/opt/adventure-chat'
      - '/opt/adventure-chat/node_modules'
    ports:
      - "3000:3000"
      - "8080:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
