FROM node:12.15.0-alpine
WORKDIR /opt/adventure-chat
COPY package.json yarn.lock ./
RUN yarn
COPY . ./
RUN yarn build

FROM nginx:alpine
COPY --from=0 /opt/adventure-chat/build /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
