version: '3'
services:
  nats:
    image: nats:2
    ports:
      - "4222:4222"
    expose:
      - "4222"
    hostname: nats
    networks:
      - internal
  mysqlauth:
    build:
      context: ./../adventure-chat-db
      dockerfile: Dockerfile.auth
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=nanjing1
    networks:
      - internal
  mysqlaccounts:
    build:
      context: ./../adventure-chat-db
      dockerfile: Dockerfile.accounts
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=nanjing1
    networks:
      - internal
  mysqlchat:
    build:
      context: ./../adventure-chat-db
      dockerfile: Dockerfile.chat
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=nanjing1
    networks:
      - internal
  adventure:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - nats
      - mysqlaccounts
      - mysqlauth
      - mysqlchat
    ports:
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
    expose:
      - "3001"
      - "3002"
      - "3003"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    networks:
      - internal
networks:
  internal:
