version: "3.3"

services:
  accouts-api:
    build:
      context: .
    image: adventure-chat-server
    container_name: accounts-api
    env_file: docker-compose.env
    environment:
      SERVICES: accounts-api # Runner will start only the 'api' service in this container
      PORT: 3001    # Port of API gateway
    depends_on:
      - nats
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gw.rule=PathPrefix(`/`)"
      - "traefik.http.services.api-gw.loadbalancer.server.port=3002"
    networks:
      - internal
    stdin_open: true

  nats:
    image: nats:2
    labels:
      - "traefik.enable=false"
    networks:
      - internal
    stdin_open: true

  traefik:
    image: traefik:v2.1
    command:
      - "--api.insecure=true" # Don't do that in production!
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - 3002:80
      - 3003:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal
      - default

networks:
  internal: