version: '3'
services:
  adventure:
    build:
      context: ""
      dockerfile: Dockerfile.deploy
    volumes:
      - './adventure-chat-front-end:/opt/adventure-chat'
      - '/opt/adventure-chat/node_modules'
    ports:
      - "8080:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NGINX_HOST=adventurechat.com
      - NGINX_PORT=80
    stdin_open: true
