version: '3'
services:
  fe:
    build:
      context: ""
      dockerfile: Dockerfile
    volumes:
      - '.:/opt/adventure-chat'
      - '/opt/adventure-chat/node_modules'
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
